packages:
  - "apps/*"
  - "packages/*"
  - "contracts"
allowBuilds:
  '@clerk/shared': true
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bufferutil: set this to true or false
  keccak: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.129'
  - '@ai-sdk/openai@3.0.71'
  - '@ai-sdk/provider-utils@4.0.29'
  - ai@6.0.203
  - '@ai-sdk/react@3.0.205'
